### ISSUE TITLE
Fine-tuning TGIF-QA FrameQA

### ISSUE THREAD

**Issue by wonjiny** [showlab/all-in-one#16]
TGIF dataset folder is flawless which is checked by md5. 
However, I have an error.

$ python run.py with data_root=DATAROOT num_gpus=1 num_nodes=1 num_frames=3 per_gpu_batchsize=8 task_finetune_tgifqa load_path="pretrained/all-in-one-plus-224.ckpt"

initalize data augmentation for a100 gpus
convert to numpy
^MValidation sanity check: 0it [00:00, ?it/s]ERROR - AllInOne - Failed after 0:00:05!
Traceback (most recent calls WITHOUT Sacred internals):
  File "run.py", line 84, in main
    trainer.fit(model, datamodule=dm)
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 473, in fit
    results = self.accelerator_backend.train()
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 152, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 305, in ddp_train
    results = self.train_or_test()
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 69, in train_or_test
    results = self.trainer.train()
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in train
    self.run_sanity_check(self.get_model())
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 693, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 596, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 235, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/myhome/all-in-one/AllInOne/datasets/tgif.py", line 87, in __getitem__
    image_tensor = self.get_video(sample)
  File "/myhome/all-in-one/AllInOne/datasets/video_base_dataset.py", line 107, in get_video
    imgs = self.get_raw_video(sample).permute(1, 0, 2, 3)  # to cthw
  File "/myhome/all-in-one/AllInOne/datasets/tgif.py", line 55, in get_raw_video
    imgs, idxs, vlen = read_frames_gif(abs_fp, self.num_frames, mode=self.split)
  File "/myhome/all-in-one/AllInOne/datasets/video_base_dataset.py", line 292, in read_frames_gif
    gif = imageio.get_reader(video_path)
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/imageio/core/functions.py", line 186, in get_reader
    return format.get_reader(request)
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/imageio/core/format.py", line 170, in get_reader
    return self.Reader(self, request)
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/imageio/core/format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/imageio/plugins/pillowmulti.py", line 60, in _open
    return PillowFormat.Reader._open(self)
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 138, in _open
    as_gray=as_gray, is_gray=_palette_is_grayscale(self._im)
  File "/myhome/.conda/envs/allinone/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 689, in _palette_is_grayscale
    palette = np.asarray(pil_image.getpalette()).reshape((256, 3))
**ValueError: cannot reshape array of size 96 into shape (256,3)**

**Comment by wonjiny** [comment]
Sorry, one gif is cracked. :(
